### ISSUE TITLE
1.16 deployment doesn't work on older clusters

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-driver-host-path#118]
New CI jobs testing 1.16 deployment on older K8s versions is failing because of the dependency on the new volumeLifecycleModes:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-csi-1-16-on-kubernetes-1-15/1191821907750555651
```
error: error validating "STDIN": error validating data: ValidationError(CSIDriver.spec): unknown field "volumeLifecycleModes" in io.k8s.api.storage.v1beta1.CSIDriverSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

I think this is working as intended since the 1.16 deployment depends on new APIs added in K8s 1.16.  I think that means we should remove any CI jobs that test newer deployments against older versions.  @pohly wdyt?  

/kind failing-test

**Comment by pohly** [comment]
> I think that means we should remove any CI jobs that test newer deployments against older versions. 

Agreed. Those jobs would have been useful if a) they worked (obviously... :grin: ) and b) if we wanted to support running newer sidecars on older Kubernetes releases. With the interpretation of "recommended Kubernetes version" as "this is what we released for, don't run on anything older even if it would work", we no longer do the latter.

**Comment by BenTheElder** [comment]
will this mean actually dropping support for older versions, or just for the deployment?
if I use a custom deployment can I support older kubernetes versions?

**Comment by msau42** [comment]
Our 1.16 version of the deployment specs uses a new api field introduced in 1.16.

So if you want to deploy on an older cluster, the deployment spec should not use the new field (and therefore not support the new 1.16 functionality)

**Comment by msau42** [comment]
/close
Thanks!
