### ISSUE TITLE
Failed to run hack/e2e-hostpath.sh with latest csi-test v3.0.0

### ISSUE THREAD

**Issue by Madhu-1** [kubernetes-csi/csi-driver-host-path#150]
Updated   version from `v1.0.0-rc2` to `v3.0.0` in `hack/get-sanity.sh`
Run `./hack/e2e-hostpath.sh`  failed with below error

```bash
./hack/e2e-hostpath.sh 
Downloading csi-test from https://github.com/kubernetes-csi/csi-test/releases/download/v3.0.0/csi-sanity-v3.0.0.linux.amd64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
cp: cannot stat '/tmp/csi-sanity/csi-sanity': No such file or directory
make: *** No rule to make target 'hostpath'.  Stop.
sudo: _output/hostpathplugin: command not found
sudo: /home/mrajanna/workspace/bin/csi-sanity: command not found
kill: sending signal to 3643838 failed: No such process
```
as the csi-test is release doesn't container linux-amd64 tar file and  `make hostpath` command is also not present in csi-driver-host-path

**Comment by Madhu-1** [comment]
cc @pohly

**Comment by pohly** [comment]
`hack/get-sanity.sh` cannot depend on pre-compiled binaries for recent csi-test release because those don't get published anymore. It would have to get and build the source code instead.

Building the hostpath driver probably also changed.
