### ISSUE TITLE
PreStop hook always fails

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/csi-driver-host-path#175]
csi-hostpath manifests here and in kubernetes/kubernetes contains PreStop hook to remove the driver socket before containers dies.

Since node-driver-registrar container is distroless, the hook always fails:

`
I0330 08:31:17.836238    1362 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"ephemeral-5231", Name:"csi-hostpathplugin-0", UID:"ad6006d7-6425-4661-829e-8106640183fb", APIVersion:"v1", ResourceVersion:"1676", FieldPath:"spec.containers{node-driver-registrar}"}): type: 'Warning' reason: 'FailedPreStopHook' Exec lifecycle hook ([/bin/sh -c rm -rf /registration/csi-hostpath /registration/csi-hostpath-reg.sock]) for Container "node-driver-registrar" in Pod "csi-hostpathplugin-0_ephemeral-5231(ad6006d7-6425-4661-829e-8106640183fb)" failed - error: command '/bin/sh -c rm -rf /registration/csi-hostpath /registration/csi-hostpath-reg.sock' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused \"exec: \\\"/bin/sh\\\": stat /bin/sh: no such file or directory\": unknown\r\n"
`

Sadly, events are not available in prow job artifacts, it's visible only in kubelet logs.

**Comment by Madhu-1** [comment]
@jsafrane this is same as https://github.com/kubernetes-csi/node-driver-registrar/issues/21 will be fixed by https://github.com/kubernetes-csi/node-driver-registrar/pull/61

**Comment by jsafrane** [comment]
Nice! I'll remove the PreStop from manifests here, they don't work and there is no plan to add shell to node-driver-registrar.
/assign
