### ISSUE TITLE
Hostpath driver fails to delete volumesnapshotcontent whose DeletionPolicy is patched to `Delete` 

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-csi/csi-driver-host-path#178]
What happened: 
A patched volumesnapshotcontent object does not get deleted.

These are the steps that I followed:
1. Create a volumesnapshot using a volumesnapshotclass with `DeletionPolicy` Retain. This created the volumesnapshot and the volumesnapshotcontent object with `DeletionPolicy: Retain`
2. Delete the volumesnapshot object created above. Now because the `DeletionPolicy` was `Retain` the volumesnapshotcontent object is preserved.
3. Patch the volumesnapshotcontent object to set its `DeletionPolicy` to `Delete`
4. Now delete the volumesnapshotcontent. At this step, the object's finalizer `snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection` doesn't remove itself and the deletion just sits at the terminal.

What I expected:
I expected that the object to be deleted.

**Comment by ashish-amarnath** [comment]
cc @xing-yang 
Is this a valid scenario for the CSI drivers? Is my expectation from the issue correct?

**Comment by xing-yang** [comment]
@ashish-amarnath Can you test this using the latest code from external-snapshotter?  This might be the same issue as reported here: https://github.com/kubernetes-csi/external-snapshotter/issues/292.  We are cutting release 2.1.1 soon with this fix so you can wait for that as well.

**Comment by ashish-amarnath** [comment]
Will give that a try. Thanks!

**Comment by xing-yang** [comment]
@ashish-amarnath, 2.1.1 is released for external-snapshotter.

**Comment by ashish-amarnath** [comment]
This was a false alarm.
/close
