### ISSUE TITLE
Error in deploying csi-hostpath-driverinfo.yaml <STDIN - Cant find KIND - CSIDriver> on 15,16 and 17 K8s 

### ISSUE THREAD

**Issue by lmcdasm** [kubernetes-csi/csi-driver-host-path#187]
Hello.

I have just cloned the repo for the host-path-csi-project:
https://github.com/kubernetes-csi/csi-driver-host-path

i have tried with 15, 16 and now on 17.4 K8S (that is what this log is).

When i do the deployment (again, im using 17+ K8S here instructions here but i got stuck at both places) i get the same error when i do the command:

 deploy/kubernetes-latest/deploy.sh

as outlined here: https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/docs/deploy-1.17-and-later.md

ERROR during deployment:
deploying hostpath components
   deploy/kubernetes-latest/hostpath/csi-hostpath-attacher.yaml
        using           image: quay.io/k8scsi/csi-attacher:v3.0.0-rc1
service/csi-hostpath-attacher unchanged
statefulset.apps/csi-hostpath-attacher unchanged
   deploy/kubernetes-latest/hostpath/csi-hostpath-driverinfo.yaml
error: unable to recognize "STDIN": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
modified version of deploy/kubernetes-latest/hostpath/csi-hostpath-driverinfo.yaml:
apiVersion: storage.k8s.io/v1

i have verified that the CRDs are installed and i can see that the api "storage.k8s.io/v1" has a "Kind" CSIDriver (see output of kubectl api-resources).

[dasm@ip-0 csi-driver-host-path]$ kubectl api-resources
volumesnapshotclasses                          snapshot.storage.k8s.io        false        VolumeSnapshotClass
volumesnapshotcontents                         snapshot.storage.k8s.io        false  VolumeSnapshotContent
volumesnapshots                                snapshot.storage.k8s.io        true         VolumeSnapshot
csidrivers                                     storage.k8s.io                 false        CSIDriver
csinodes                                       storage.k8s.io                 false        CSINode
storageclasses                    sc           storage.k8s.io                 false        StorageClass
volumeattachments                              storage.k8s.io                 false        VolumeAttachment

Here is my K8s version information:

[dasm@ip-0  csi-driver-host-path]$ kubectl version --short
Client Version: v1.18.3
Server Version: v1.17.4
[dasm@ip-0 csi-driver-host-path]$

**Comment by pohly** [comment]
`deploy/kubernetes-latest/deploy.sh` is a symlink for the latest deployment, which is currently `kubernetes-1.18`. That deployment is not compatible with 1.17 because the version of CSIDriver changed from `storage.k8s.io/v1beta1` to `storage.k8s.io/v1`.

If you use the `kubernetes-1.17` deployment, it should work.

This probably should be explained better in the instructions if it wasn't clear. If you have suggestions for how it should be worded, then a PR would be welcome.

**Comment by lmcdasm** [comment]
Hey there.

Argh.. i should have just chased down the softlink.. thanks for pointing
that out!

Cheers,
Daniel
