### ISSUE TITLE
csi-snapshotter pod throws an error "volumeID is not exist"

### ISSUE THREAD

**Issue by aayush-rangwala** [kubernetes-csi/csi-driver-host-path#188]
While trying out the `VolumeSnapshot`, getting the error intermitently:

`Failed to create snapshot: failed to take snapshot of the volume,         pvc-7cf67f78-a5b9-11ea-81ba-42010a8e0fc6: "rpc error: code = Internal desc         = volumeID is not exist`

where it is definitely sure that the pvc `pvc-7cf67f78-a5b9-11ea-81ba-42010a8e0fc6` exists in the namespace and is accessible

Tried to get the logs of csi-snapshotter and csi-hostpathplugin logs, had same errors.

k8s version: 1.14, 1.15, 1.16
CSI versions: 1.2.0, 1.3.0

`VolumeSnapshotClass` and `VolumeSnapshot` are correct as per the docs and also It was working some time with the same listed setups and sometime it not

**Comment by scuzhanglei** [comment]
it's because the plugin don't discover existed volumes on the disk，same as #55

**Comment by aayushrangwala** [comment]
@scuzhanglei  yeah, but isn't it better to resync the cache (maps) after each restarting the pod. It could be something like when the maps are initialised, we can update/recreate the map
