### ISSUE TITLE
k8s 1.17: csi-hostpath-snapclass is not created during the driver deployment

### ISSUE THREAD

**Issue by sedovalx** [kubernetes-csi/csi-driver-host-path#199]
I'm trying to deploy the driver on minikube with `--kubernetes-version v1.17.9`, so I have installed CRDs and then have run `csi-driver-host-path/deploy/kubernetes-1.17/deploy.sh` for that. The last line in the deploy log was "deploying snapshotclass based on snapshotter version". And then, when I tried to create a snapshot with `examples/csi-snapshot-v1beta1.yaml` I've got the following error for the `new-snapshot-demo` volume snapshot:
```
$ kubectl describe volumesnapshot                                                                
Name:         new-snapshot-demo
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"snapshot.storage.k8s.io/v1beta1","kind":"VolumeSnapshot","metadata":{"annotations":{},"name":"new-snapshot-demo","namespace...
API Version:  snapshot.storage.k8s.io/v1beta1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2020-09-14T10:21:34Z
  Generation:          1
  Resource Version:    59736
  Self Link:           /apis/snapshot.storage.k8s.io/v1beta1/namespaces/default/volumesnapshots/new-snapshot-demo
  UID:                 1acdcca0-2cbd-4825-b15d-1eb6edd793b8
Spec:
  Source:
    Persistent Volume Claim Name:  csi-pvc
  Volume Snapshot Class Name:      csi-hostpath-snapclass
Status:
  Error:
    Message:     Failed to get snapshot class with error failed to retrieve snapshot class csi-hostpath-snapclass from the informer: "volumesnapshotclass.snapshot.storage.k8s.io \"csi-hostpath-snapclass\" not found"
    Time:        2020-09-14T10:21:34Z
  Ready To Use:  false
Events:
  Type     Reason                  Age    From                 Message
  ----     ------                  ----   ----                 -------
  Warning  GetSnapshotClassFailed  4m23s  snapshot-controller  Failed to get snapshot class with error failed to retrieve snapshot class csi-hostpath-snapclass from the informer: "volumesnapshotclass.snapshot.storage.k8s.io \"csi-hostpath-snapclass\" not found"
```

In the "deploy-hostpath.sh" I see that the `csi-hostpath-snapshotclass.yaml` applied for k8s 1.16 only. Is it right? Am I doing something wrong?

**Comment by sedovalx** [comment]
The problem happened because I was calling the `deploy.sh` script from inside the `kubernetes-1.17` directory. It should be called from the outside of it.

**Comment by pohly** [comment]
/reopen

It should be possible to invoke the script anywhere. That's what `BASE_DIR` https://github.com/kubernetes-csi/csi-driver-host-path/blob/d46b19b97909e779d28e90cb8c5eb091d5fc5b2b/deploy/util/deploy-hostpath.sh#L14 is for.

I'm not sure why it is failing, but the issue seems legitimate.

/help

**Comment by sedovalx** [comment]
`BASE_DIR` is `.` if I do
```
cd deploy/kubernetes-1.17
./deploy.sh
```
but it contains `kubernetes-1.17` if
```
./deploy/kubernetes-1.17/deploy.sh
```

MacOS, zsh

**Comment by pohly** [comment]
Bingo: https://github.com/kubernetes-csi/csi-driver-host-path/blob/d46b19b97909e779d28e90cb8c5eb091d5fc5b2b/deploy/util/deploy-hostpath.sh#L222

That only works when `BASE_DIR` includes the "kubernetes-x.yy" name. The check shouldn't make that assumption and instead use
`driver_version="$(basename "$(readlink -f "${BASE_DIR}")" )"`

Does `readlink -f` work under MacOS? It's from GNU coreutils.

**Comment by sedovalx** [comment]
No, seems it doesn't work on MacOS. Here is an explanation and a workaround https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Comment by pohly** [comment]
@sedovalx a simple `cd + pwd` should do the trick here. Do you think you can come up with a PR?

**Comment by sedovalx** [comment]
Sorry - I don't have much knowledge in bash. Can do if you tell me exactly what to change :)
