### ISSUE TITLE
Controllerserver check for already existing volume name

### ISSUE THREAD

**Issue by YiannisGkoufas** [kubernetes-csi/csi-driver-host-path#205]
Hi there,

was just looking at controllerserver and especially in this line https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/pkg/hostpath/controllerserver.go#L124 and I am a bit confused.

What is the case where a new pvc with the same name gets created?

Thanks!

**Comment by pohly** [comment]
`CreateVolume` might be invoked more than once with the exact same parameters, for example if the response is lost and never reaches the caller, or when the caller aborts the first instance of the call because of a timeout.

The keyword here is "idempotency".

**Comment by YiannisGkoufas** [comment]
Perfect, makes sense. Thanks for the prompt response!
