### ISSUE TITLE
make hostpath Don't give expected output

### ISSUE THREAD

**Issue by Kartik494** [kubernetes-csi/csi-driver-host-path#207]
When i run command "make hostpath" from  my root directory i got the error as "make: *** No rule to make target 'hostpath'.  Stop."
and in make file the argument is used for build is: all 
CMDS=hostpathplugin
all: build

include release-tools/build.make

However when i changes the argument all to hostpath then the command "make hostpath" is executed 

CMDS=hostpathplugin
hostpath: build

include release-tools/build.make

So in Docs should we update make hostpath command to make all ?

**Comment by pohly** [comment]
Works for me. I'm using:
- GNU Make 4.2.1
- Debian GNU/Linux 10 (buster)
- csi-driver-host-path master (= 123fa4eed59e3609c8498d8bf0d368d0b734e172).

`all` depends on `build`, which depends on `$(CMDS:%=build-%)`.

I've not checked whether the latter is part of POSIX make or specific to GNU Make.

**Comment by Kartik494** [comment]
Hi @pohly  Thanks for input ,  could you please suggest is there any pre-requisite i have to follow for running the command make hostpath in my envoirment. Is the GNU Make is specific to be at 4.2.1 version? Because i am still facing issue in that , only command is working for me is when i change this to make all or make. Please Suggest

**Comment by pohly** [comment]
Now I get it. It's failing for your because you literally are running `make hostpath`.

That simply isn't a valid invocation because there is no such build target, as make is pointing out.

If you want to build the binary, use `make` without a build target. That works in any of the Kubernetes-CSI repos, so you don't have to figure out what the binary is called.

**Comment by Kartik494** [comment]
> If you want to build the binary, use make without a build target. That works in any of the Kubernetes-CSI repos, so you don't have to figure out what the binary is called.

@pohly  Yes when i use without build target then it works fine for me i.e by simply running make command , i will be closing this issue.
Thanks
