### ISSUE TITLE
make hostpath failed

### ISSUE THREAD

**Issue by silenceper** [kubernetes-csi/csi-driver-host-path#226]
follow readme:
```shell
$ make hostpath
make: *** No rule to make target 'hostpath'.  Stop.
```

when i use `make` build success，Is the readme wrong?

> platform:  Mac And Linux

**Comment by pohly** [comment]
> Is the readme wrong?

Yes. We have the same generic build targets (`make build`, `make push`, ...) in all repos now. To build an individual command in a repo which has more than one, use `make build-<cmd name>` where `<cmd name>` is one of the `CMD` items in the top-level Makefile.

Care to submit a PR which fixes this?
