### ISSUE TITLE
k8s.gcr.io/sig-storage/hostpathplugin:v1.5.0 not found: manifest unknown

### ISSUE THREAD

**Issue by colin-mccarthy** [kubernetes-csi/csi-driver-host-path#241]
Hello,

It appears the  hostpathplugin:v1.5.0 container image doesn't exist on the k8s.gcr.io container registry.

```
MacBook-Pro ~ % docker pull k8s.gcr.io/sig-storage/hostpathplugin:v1.5.0
Error response from daemon: manifest for k8s.gcr.io/sig-storage/hostpathplugin:v1.5.0 not found: manifest unknown: Failed to fetch "v1.5.0" from request "/v2/sig-storage/hostpathplugin/manifests/v1.5.0".
```
```
MacBook-Pro ~ % docker pull k8s.gcr.io/sig-storage/hostpathplugin:v1.4.0
v1.4.0: Pulling from sig-storage/hostpathplugin
b538f80385f9: Pull complete 
3b1dbe076a84: Pull complete 
de0206867a43: Pull complete 
Digest: sha256:d2b357bb02430fee9eaa43b16083981463d260419fe3acb2f560ede5c129f6f5
Status: Downloaded newer image for k8s.gcr.io/sig-storage/hostpathplugin:v1.4.0
k8s.gcr.io/sig-storage/hostpathplugin:v1.4.0
```

**Comment by pohly** [comment]
We are in the process of creating the v1.5.0 release. It starts with
- [x] bumping up the version number in the manifest,
- [ ] continues with tagging the release and
- [ ] ends with promoting the image.

**Comment by pohly** [comment]
v1.5.0 image is available:

https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/sig-storage/hostpathplugin@sha256:de166db2f9245cd0cccacfea9527f7e4c25816fde401e920163b5c17637daad1/details?tab=info

/close
