### ISSUE TITLE
Hostpath driver does not export volume metrics

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubernetes-csi/csi-driver-host-path#273]
The hostpath driver does not export volume metrics, can not see any kubelet_volume_stats_* metrics in Prometheus. 

Per CSI [spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetvolumestats):
```
A Node plugin MUST implement this RPC call if it has GET_VOLUME_STATS node capability or VOLUME_CONDITION node capability. NodeGetVolumeStats RPC call returns the volume capacity statistics available for the volume.
```

However, the hostpath driver does not enable the GET_VOLUME_STATS node capability, per https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/pkg/hostpath/nodeserver.go#L317 . It only enables the VOLUME_CONDITION node capability.

**Comment by stoneshi-yunify** [comment]
I'd like to submit a PR to fix this issue. Could someone assign this issue to me? Thanks.

**Comment by pohly** [comment]
/assign @stoneshi-yunify 

Might not work, though, if you aren't a collaborator. We'll see...
