### ISSUE TITLE
distributed-on-master failing

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes-csi/csi-driver-host-path#274]
The [distributed-on-master](https://k8s-testgrid.appspot.com/sig-storage-csi-ci#distributed-on-master) test has been failing since April 7th.

Taking [a sample error](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-csi-distributed-on-kubernetes-master/1382467134730276864/build-log.txt), it looks like the root cause is a missing `test-driver.yaml`:
```
sed: can't read /home/prow/go/pkg/csiprow.z0lNIIs8xX/test-driver.yaml: No such file or directory
```

cc @msau42 @pohly

**Comment by pohly** [comment]
I have a fix for that in PR https://github.com/kubernetes-csi/csi-driver-host-path/pull/253

I know, should have been a separate PR, but I was expecting that one to merge a bit sooner.

**Comment by chrishenzie** [comment]
@pohly Thanks for the speedy fix! It looks like there was one more test failure in [the most recent run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-csi-distributed-on-kubernetes-master/1382829568221515776).

**Comment by pohly** [comment]
> It looks like there was one more test failure in [the most recent run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-csi-distributed-on-kubernetes-master/1382829568221515776).

That looks like a timing flake. Let's keep this issue open and monitor that a bit longer.

/reopen

**Comment by pohly** [comment]
Hmm, occurred twice already. I'll check...

**Comment by pohly** [comment]
`External Storage [Driver: hostpath.csi.k8s.io] [Testpattern: Dynamic PV (immediate binding)] topology should provision a volume and schedule a pod with AllowedTopologies` is still flaky.

Let's investigate as part of this issue.

**Comment by pohly** [comment]
The reason for that failure was identified as problem in external-provisioner and fixed in https://github.com/kubernetes-csi/external-provisioner/pull/612.

We can fix the job by updating to the latest external-provisioner.

**Comment by pohly** [comment]
After merging PR #280, the job started to pass: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-csi-distributed-on-kubernetes-master/1389537313842794496
