### ISSUE TITLE
RFE:  kind  sample / easy installation using kustomize

### ISSUE THREAD

**Issue by wstrange** [kubernetes-csi/csi-driver-host-path#318]
I have a GitHub pipeline where I want to test an operator that uses VolumeSnapshots.

Setting up `kind` is relatively easy, and I have this working. But getting the CSI hostpath provisioner working in a github workflow is challenging.  It would involve cloning this repo and running the installer. Possible I suppose - but awkward.

What would be neat is a kustomize deployment where kind could do something like:

`kustomize build https://github.com/kubernetes-csi/csi-driver-host-path/kind/ | kubectl apply -f -` 

Or something like it... 

I.e. lower friction to get the hostpath provisioner deployed for testing

**Comment by pohly** [comment]
There's not anything special about kind, right?

That aside, supporting kustomize makes sense and could replace or simplify the current `deploy-hostpath.sh` script.

/help
