### ISSUE TITLE
k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.PersistentVolume: failed to list *v1.PersistentVolume: Unauthorized

### ISSUE THREAD

**Issue by bibibubu999** [kubernetes-csi/csi-driver-host-path#322]
**What happened:**
I'm new to Kubernetes, has deployed a cluster with master and 1 node (v1.22). but stuck at installing the CSI Hostpath Driver. Hope to get some help from your guys:
NAME           STATUS   ROLES                  AGE   VERSION
kulk8smaster   Ready    control-plane,master   8d    v1.22.0
kulk8snode1    Ready    <none>                 8d    v1.22.0

**Error:**

W0814 17:58:06.723058       1 reflector.go:436] k8s.io/client-go/informers/factory.go:134: watch of *v1.VolumeAttachment ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0814 17:58:06.723156       1 reflector.go:436] k8s.io/client-go/informers/factory.go:134: watch of *v1.PersistentVolume ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
I0814 17:58:07.576167       1 reflector.go:255] Listing and watching *v1.VolumeAttachment from k8s.io/client-go/informers/factory.go:134
I0814 17:58:07.648817       1 reflector.go:255] Listing and watching *v1.PersistentVolume from k8s.io/client-go/informers/factory.go:134
E0814 17:58:07.714433       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.PersistentVolume: failed to list *v1.PersistentVolume: Unauthorized
E0814 17:58:07.714490       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.VolumeAttachment: failed to list *v1.VolumeAttachment: Unauthorized
I0814 17:58:09.470569       1 reflector.go:255] Listing and watching *v1.PersistentVolume from k8s.io/client-go/informers/factory.go:134
E0814 17:58:09.475555       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.PersistentVolume: failed to list *v1.PersistentVolume: Unauthorized
I0814 17:58:09.798181       1 reflector.go:255] Listing and watching *v1.VolumeAttachment from k8s.io/client-go/informers/factory.go:134
E0814 17:58:09.803133       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.VolumeAttachment: failed to list *v1.VolumeAttachment: Unauthorized
I0814 17:58:14.327269       1 reflector.go:255] Listing and watching *v1.PersistentVolume from k8s.io/client-go/informers/factory.go:134
E0814 17:58:14.342421       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.PersistentVolume: failed to list *v1.PersistentVolume: Unauthorized
I0814 17:58:15.607972       1 reflector.go:255] Listing and watching *v1.VolumeAttachment from k8s.io/client-go/informers/factory.go:134
E0814 17:58:15.614751       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.VolumeAttachment: failed to list *v1.VolumeAttachment: Unauthorized
I0814 17:58:22.113852       1 reflector.go:255] Listing and watching *v1.PersistentVolume from k8s.io/client-go/informers/factory.go:134
E0814 17:58:22.118194       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.PersistentVolume: failed to list *v1.PersistentVolume: Unauthorized
I0814 17:58:24.452587       1 reflector.go:255] Listing and watching *v1.VolumeAttachment from k8s.io/client-go/informers/factory.go:134
E0814 17:58:24.457977       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.VolumeAttachment: failed to list *v1.VolumeAttachment: Unauthorized
I0814 17:58:38.989479       1 reflector.go:255] Listing and watching *v1.PersistentVolume from k8s.io/client-go/informers/factory.go:134
E0814 17:58:38.998399       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.PersistentVolume: failed to list *v1.PersistentVolume: Unauthorized
I0814 17:58:43.262047       1 reflector.go:255] Listing and watching *v1.VolumeAttachment from k8s.io/client-go/informers/factory.go:134
E0814 17:58:43.270432       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.VolumeAttachment: failed to list *v1.VolumeAttachment: Unauthorized

**Steps Used:**

1.	Create new storage class
Manifest.yaml

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-hostpath-sc 
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"    
provisioner: hostpath.csi.k8s.io 
reclaimPolicy: Delete 
volumeBindingMode: Immediate 
allowVolumeExpansion: true 
parameters:
  fstype: ext4

#to create the storageClass from the manifest file, save the manifest in a file manifest.yaml
kubectl apply -f manifest.yaml

2.	Before Install CSI, apply the following command

SNAPSHOTTER_VERSION=v4.0.0 
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml 
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml 
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml 

# install snapshot controller
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml 
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml

3.	Install CSI Host Driver

Install the CSI Hostpath Driver
$ git clone https://github.com/kubernetes-csi/csi-driver-host-path.git
$ cd csi-driver-host-path
$ ./deploy/kubernetes-latest/deploy.sh

**Comment by pohly** [comment]
How did you set up this cluster, i.e. with which tool?

Which pod is reporting these permission issues?

Did `deploy.sh` perhaps report any errors?

**Comment by bibibubu999** [comment]
@pohly  

The issue has been fixed, after the VolumeSnapshot CRDs and snapshot controller installation, I run "kubectl get pods -w" and noticed the snapshot-controller-0 remained in pending status, waited more an hour plus with no luck, So I rebooted the master and nodes, after the reboot,  snapshot-controller-0 status changed to "Running". 

Installation of the CSI Hostpath Driver run completed successfully after that :) .
