### ISSUE TITLE
Prevent csi pod moving to another node?

### ISSUE THREAD

**Issue by rahmataw** [kubernetes-csi/csi-driver-host-path#352]
Hi, I deployed CSI hostpath on top kubernetes with 2 worker node. Righ now, my pod `snapshot-controller-0` and `csi-hostpathplugin-0` deployed on worker2. I need to reboot this server. How to prevent this pod from moving to worker1? I want to avoid data loss due to this pod moving to worker1.

Note:
I checked my node label and there is a label `topology.hostpath.csi/node=worker-2` but when I check on `snapshot-controller-0` and `csi-hostpathplugin-0` there are no nodeSelectore defined.

**Comment by pohly** [comment]
That sounds like you are using csi-host-path-driver for some real production workloads. Please don't do that, it is strictly for testing and demo purposes.

**Comment by rahmataw** [comment]
> That sounds like you are using csi-host-path-driver for some real production workloads. Please don't do that, it is strictly for testing and demo purposes.

Actually it is staging env and it is ok if the data lost, just curious for the posibility.
