### ISSUE TITLE
Missing a piece of the URL, for the CRD installation

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes-csi/csi-driver-host-path#367]
https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/docs/deploy-1.17-and-later.md

The version 2.0.1 is outdated:

`no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`

When changing to 6.0.1, the url is wrong:

`server reported 404 Not Found, status code=404`

----

There seems to be an extra "client" directory added, so better update the example ?

https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd

Even bettter, to make it available as a script (.sh) to avoid all them extra `$ ` characters.

```sh
#!/bin/sh

# Change to the latest supported snapshotter version
SNAPSHOTTER_VERSION=v6.0.1

# Apply VolumeSnapshot CRDs
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml

# Create snapshot controller
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/${SNAPSHOTTER_VERSION}/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml

```

**Comment by Ryan-Barlow-Nimbox** [comment]
Hello,

I am getting the exact same issue/error on this did you find a way around it?

Many Thanks
Ryan

**Comment by afbjorklund** [comment]
The modified commands are listed above

**Comment by pohly** [comment]
Can you perhaps create a PR?

**Comment by Kartik494** [comment]
> 

that's because in external-snapshotter 3.0 onwards CRD's are moved to under `/client` directory , please find the link 
https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd
Feel free to raise a PR for the same.
