### ISSUE TITLE
Host Path PV Encryption

### ISSUE THREAD

**Issue by vishal549** [kubernetes-csi/csi-driver-host-path#384]
Hi,

I am planning to implement hostPath persistent volumes with encryption. While searching I got this link. How can I enhance this driver to add encryption? So that data stored in PV is encrypted. Can anyone please provide suggestions on this?

Thanks,
Vishal.

**Comment by pohly** [comment]
Please don't use this driver for production usage. We use it for testing Kubernetes and the CSI sidecars. For that, encryption is not needed, so I doubt that we would accept a PR which adds it.
