### ISSUE TITLE
Add description for this repository

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes-csi/csi-driver-host-path#4]
This repository needs a descriptive text in the description box.

**Comment by pohly** [comment]
/remove-lifecycle stale

This probably needs to be done by the infrastructure team now? Not sure what the process is, though.

**Comment by vladimirvivien** [comment]
/assign @saad-ali
/assign @msau42  
Before I close this issue, I wanted to point out the hostpath repo does not have a description. Not sure who would do this.

cc @pohly

**Comment by msau42** [comment]
I think I can do it.  Can you suggest a description?

**Comment by vladimirvivien** [comment]
`A sample CSI Driver implementation with hostpath functionalities` 😬 

What do you think 
@msau42 @pohly

**Comment by msau42** [comment]
```
A sample CSI Driver that creates a local directory as a volume on a single node
``` 
???

**Comment by vladimirvivien** [comment]
@msau42 yours reads much better!

**Comment by msau42** [comment]
done
/close
