### ISSUE TITLE
KEP-3751 - VAC Hostpath Driver Implementation

### ISSUE THREAD

**Issue by sunnylovestiramisu** [kubernetes-csi/csi-driver-host-path#479]
Currently in https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/pkg/hostpath/controllerserver.go#L496 ControllerModifyVolume is marked as not implemented.

This implementation will help us test the alpha feature.

**Comment by carlory** [comment]
I raise a pr but I don't know which attributes of a linux directory or device can be mutable? Can you give me some guide?

@sunnylovestiramisu @msau42

**Comment by sunnylovestiramisu** [comment]
@carlory We talked about this at the CSI meeting today:

1. We should look at https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/pkg/state/state.go#L39 and see if there is any attributes that can be modified first(so far I think none of them can be modified)
2. Since the host path driver has two modes, we can add fake params in the mock client for modify volume, and then add unit tests to verify the change

**Comment by sunnylovestiramisu** [comment]
From the comment in resizer: https://github.com/kubernetes-csi/external-resizer/pull/351#pullrequestreview-1777987701

The test cases we should cover with the mock client:

1. When a VAC is applied to a PVC that was created before VAC feature existed.
2. When VAC is applied to a PVC that was provisioned without any VAC (but after the feature existed in k8s and external-provisioner).
3. When VAC is applied rapidly to a PVC before previous VAC had a chance to be applied completely.
4. When both VAC and volume expansion change is performed at the same time.
5. When both VAC and volume expansion change is performed at the same time, but VAC change keeps failing. Can volume still be expanded for new size?
