### ISSUE TITLE
Symlinks broken in /deploy

### ISSUE THREAD

**Issue by hairyhum** [kubernetes-csi/csi-driver-host-path#504]
Currently symlinks for [kubernetes-latest](https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/deploy/kubernetes-latest) and [kubernetes-1.28](https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/deploy/kubernetes-1.28) do not resolve correctly, must've been introduced in https://github.com/kubernetes-csi/csi-driver-host-path/commit/482f780e9e4b086d0b37110739a944cd64b9d504

To reproduce:
```
git clone git@github.com:kubernetes-csi/csi-driver-host-path.git
cd csi-driver-host-path
ls -R deploy/kubernetes-latest/ 
```

In `master` it fails with `ls: deploy/kubernetes-latest/: No such file or directory`

In `v1.12.1` it lists the directory.

**Comment by tesshuflower** [comment]
@hairyhum this appears to be fixed in the latest v1.14.0 release
