### ISSUE TITLE
topology support

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/csi-driver-host-path#54]
The hostpath driver should support topology on Kubernetes 1.14. Then applications no longer need to be scheduled manually onto the right node and we can remove that workaround from the E2E testing in Kubernetes.

It also might make the driver complete enough to serve as default storage driver in a KinD cluster.

**Comment by awels** [comment]
@pohly Hi, are you aware if any attempts to implement this have been made already? If not, I would be potentially interested in taking a stab at this.

**Comment by pohly** [comment]
Alexander Wels <notifications@github.com> writes:
> @pohly Hi, are you aware if any attempts to implement this have been made already? If not, I would be potentially interested in taking a stab at this.

No, I don't think so. Please, give it a try.

**Comment by mucahitkurt** [comment]
I'm working on this issue.

**Comment by BenTheElder** [comment]
/subscribe
thanks for this! very eager to take a look a shipping this with kind :-) https://github.com/kubernetes-sigs/kind/issues/118
