### ISSUE TITLE
map access needs lock

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-driver-host-path#72]
All `hostPathVolumes` and `hostPathSnapshots` map updates/reads need a lock.

/help
/good-first-issue

**Comment by cwdsuzhou** [comment]
It seems I have sent a PR to fix the issue long long ago, but not anyone reviewed it.

https://github.com/kubernetes-csi/csi-driver-host-path/pull/17

**Comment by cwdsuzhou** [comment]
If I should reopen it ?

**Comment by pohly** [comment]
/remove-lifecycle stale

> All hostPathVolumes and hostPathSnapshots map updates/reads need a lock.

I think we need to go further than that: we also need to serialize gRPC calls unless it is certain that they can operate in parallel. A production CSI driver may want to serialize calls that operate on the same volume and then use locks on data structures that are shared between volumes. For hostpath I think it is sufficient to serialize all volume calls with a comment that explains that this is not necessarily how a production driver would do it.

When implemented like that, we don't need locks on those data structures.
