### ISSUE TITLE
Output container logs when deployment fails

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-driver-host-path#94]
Sometimes when testing new features, it causes hostpath driver containers to crash. It would be useful to output the container logs to make debugging easier.

/help

**Comment by msau42** [comment]
/remove-lifecycle stale
@pohly is this fixed?

**Comment by pohly** [comment]
No, we still only have the output of `kubectl describe`: https://github.com/kubernetes-csi/csi-driver-host-path/blob/03f426213c3bcaf0b5d9b16b2ae6b9d08c67112a/deploy/util/deploy-hostpath.sh#L208-L213
